[project]
name = "OpenStudioLandscapes-Dagster"
description = "Dagster Feature for OpenStudioLandscapes"

[project.urls]
Homepage = "https://github.com/michimussato/OpenStudioLandscapes-Dagster"

[project.optional-dependencies]
sbom = [
    "OpenStudioLandscapes-Dagster[graphviz]",
]
nox = [
    "OpenStudioLandscapes-Dagster[testing]",
]
readme = [
    "OpenStudioLandscapesUtil-ReadmeGenerator @ git+https://github.com/michimussato/OpenStudioLandscapesUtil-ReadmeGenerator.git@v1.8.0-rc1"
]
dev = [
    "OpenStudioLandscapes-Dagster[testing]",
    "OpenStudioLandscapes-Dagster[lint]",
    "OpenStudioLandscapes-Dagster[nox]",
    "OpenStudioLandscapes-Dagster[sbom]",
    "OpenStudioLandscapes-Dagster[coverage]",
    "OpenStudioLandscapes-Dagster[readme]",
]

[tool.setuptools]
packages = [
    "OpenStudioLandscapes.Dagster"
]

[tool.dagster]
module_name = "OpenStudioLandscapes.Dagster.definitions"
code_location_name = "OpenStudioLandscapes-Dagster"
