load_from:
#  - python_package:
#      package_name: My-Skeleton-Package
#      location_name: "My Skeleton Package Location"
# Todo:
#  - [ ] dynamic workspace.yaml to be able to add dagster-shared dynamically (https://github.com/michimussato/dagster-shared)
#  - [ ] Shouldn't this be OpenStudioLandscapes.open_studio_landscapes also?
  - python_module:
      # https://github.com/michimussato/deadline-dagster
      working_directory: src
      module_name: OpenStudioLandscapes.dagster_job_processor.definitions
      location_name: "dagster_job_processor Package Location"
      # executable_path: ../.venv/bin/python
#  - python_module:
#      # Todo:
#      #  - [ ] will only work after making studio-landscapes public
#      # https://github.com/michimussato/deadline-dagster
#      working_directory: src
#      module_name: OpenStudioLandscapes.open_studio_landscapes.definitions
#      location_name: "OpenStudioLandscapes.open_studio_landscapes Package Location"
#      # executable_path: ../.venv/bin/python
